<%@ Page Language="C#" AutoEventWireup="true" CodeFile="WebPage2.aspx.cs" Inherits="WebPage2" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
    <style type="text/css">
        .auto-style1 {
            height: 665px;
            margin-left: 200px;
        }
        .auto-style2 {
            width: 535px;
        }
        </style>
</head>
<body>
    <form id="form1" runat="server">
        <asp:HiddenField ID ="HiddenID" Value ="0" runat ="server" />
        <div class="auto-style1">
            <asp:Button ID ="ButtonAddNew" runat ="server" Text="Add New" OnClick="ButtonAddNew_Click" />
            <table id="TableDetails" runat="server">
                <tr>
                    <td class="auto-style2">Name</td>
                    
            
                    <td><asp:TextBox ID="TextBoxName" runat="server" Width="180px"></asp:TextBox>  <asp:RequiredFieldValidator ID="RequiredFieldValidator1" runat="server" ControlToValidate="TextBoxName" ErrorMessage="Name is required" ForeColor="Red"></asp:RequiredFieldValidator> </td>
                </tr>

               <tr>
                   <td class="auto-style2">Phone Number</td>

                   <td> <asp:TextBox ID="TextBoxPhoneNumber" runat="server" Width="180px"></asp:TextBox> <asp:RequiredFieldValidator ID="RequiredFieldValidator2" runat="server" ControlToValidate="TextBoxPhoneNumber" ErrorMessage="Phone number is required" ForeColor="Red"></asp:RequiredFieldValidator></td>
               </tr>

                <tr>
                    <td class="auto-style2">Address</td>
                    <td> <asp:TextBox ID="TextBoxAddress" runat="server" Width="180px"></asp:TextBox>  <asp:RequiredFieldValidator ID="RequiredFieldValidator3" runat="server" ControlToValidate="TextBoxAddress" ErrorMessage="Address is required" ForeColor="Red"></asp:RequiredFieldValidator></td>
                </tr>

                <tr>
                    <td class="auto-style2"><asp:Button ID="ButtonSave" runat="server" OnClick="ButtonSave_Click" Text="Insert" Width="180px" BackColor="Lime" ForeColor="#6600FF" />
&nbsp;
            <asp:Button ID="ButtonUpdate" runat="server" BackColor="Lime" ForeColor="#6600FF" OnClick="Button1_Click" Text="Update" Width="153px" />&nbsp;&nbsp;&nbsp;&nbsp;
                        <asp:Button ID="ButtonDelete" runat="server" BackColor="Lime" ForeColor="#6600FF" OnClick="ButtonDelete_Click" Text="Delete" Width="153px" />
                    </td>
                </tr>
            </table>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" CellPadding="4" ForeColor="#333333" GridLines="None" Width="100%" OnRowDeleting="GridView1_RowDeleting" OnSelectedIndexChanged="GridView1_SelectedIndexChanged" OnRowEditing="GridView1_RowEditing">
                <AlternatingRowStyle BackColor="White" ForeColor="#284775" />
                <EditRowStyle BackColor="#999999" />
                <FooterStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <HeaderStyle BackColor="#5D7B9D" Font-Bold="True" ForeColor="White" />
                <PagerStyle BackColor="#284775" ForeColor="White" HorizontalAlign="Center" />
                <RowStyle BackColor="#F7F6F3" ForeColor="#333333" />
                <SelectedRowStyle BackColor="#E2DED6" Font-Bold="True" ForeColor="#333333" />
                <SortedAscendingCellStyle BackColor="#E9E7E2" />
                <SortedAscendingHeaderStyle BackColor="#506C8C" />
                <SortedDescendingCellStyle BackColor="#FFFDF8" />
                <SortedDescendingHeaderStyle BackColor="#6F8DAE" />
            </asp:GridView>
        </div>
    </form>
</body>
</html>
